// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF5xM7eEcnKY5YqUDb8sfsD0n7aItTzM4',
    appId: '1:290844758714:web:8f155a707d4a3ce64ee883',
    messagingSenderId: '290844758714',
    projectId: 'voya-cb3ce',
    authDomain: 'voya-cb3ce.firebaseapp.com',
    storageBucket: 'voya-cb3ce.firebasestorage.app',
    measurementId: 'G-EG09N8CTRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmdQw4ef-zUxLbAjajjWdUyWmrBdzZIc',
    appId: '1:290844758714:android:b20b8353c61ddefd4ee883',
    messagingSenderId: '290844758714',
    projectId: 'voya-cb3ce',
    storageBucket: 'voya-cb3ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFY5L-Ll5_FBXGy3ndniE6K2iMp3BeMIk',
    appId: '1:290844758714:ios:5395bf7e6547a6944ee883',
    messagingSenderId: '290844758714',
    projectId: 'voya-cb3ce',
    storageBucket: 'voya-cb3ce.firebasestorage.app',
    iosBundleId: 'com.example.vnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFY5L-Ll5_FBXGy3ndniE6K2iMp3BeMIk',
    appId: '1:290844758714:ios:5395bf7e6547a6944ee883',
    messagingSenderId: '290844758714',
    projectId: 'voya-cb3ce',
    storageBucket: 'voya-cb3ce.firebasestorage.app',
    iosBundleId: 'com.example.vnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF5xM7eEcnKY5YqUDb8sfsD0n7aItTzM4',
    appId: '1:290844758714:web:1f9ae418f85197684ee883',
    messagingSenderId: '290844758714',
    projectId: 'voya-cb3ce',
    authDomain: 'voya-cb3ce.firebaseapp.com',
    storageBucket: 'voya-cb3ce.firebasestorage.app',
    measurementId: 'G-SZ9Y9X6WSW',
  );
}
